version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd react-app && npm install && npm test
workflows:
  do_it:
    jobs:
      - build-and-test
        filters:
          branches:
            ignore:
            - master
      - heroku/deploy-via-git: 
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - heroku-deploy-test
